// ===== Catálogo Atenis Games (apenas jogos reais e jogáveis) =====
const CATEGORIES = [
  { id: "todos",     name: "Início",     icon: "🏠" },
  { id: "corrida",   name: "Corrida",    icon: "🏎️" },
  { id: "cartas",    name: "Paciência",  icon: "🃏" },
  { id: "estrategia",name: "Estratégia", icon: "👑" },
  { id: "quizes",    name: "Quizes",     icon: "🧠" },
  { id: "puzzle",    name: "Puzzle",     icon: "💣" },
  { id: "musica",    name: "Música",     icon: "🎵" },
];

const GAMES = [
  {
    id: "songless",
    title: "Songless",
    short: "Adivinhe a música ouvindo trechos que crescem — com Spotify!",
    cat: "musica",
    catName: "Música",
    rating: 4.9,
    plays: "2.8M",
    dev: "Atenis Studios",
    tags: ["Música", "Quiz", "Spotify", "Diário", "Playlists"],
    grad: "linear-gradient(135deg,#8e4bd0,#3d1a6b)",
    accent: "#b06bff",
    icon: "🎵",
    playable: true,
    embed: "",
    src: "games/songless/index.html?v=18",
    flags: ["NEW", "TOP"],
    about: [
      "Songless é o quiz musical definitivo: você ouve um trechinho de 1 segundo e tenta adivinhar a música. Errou ou pulou? O trecho cresce — 2s, 4s, 7s, 11s, 16s — até a sexta e última tentativa. Quanto antes acertar, melhor o resultado.",
      "Jogue o Desafio Diário (a mesma música pra todo mundo, uma por dia) ou o Modo Infinito com 8 playlists Atenis: Hits Brasil, Sertanejo, MPB, Pop Internacional, Rock Clássico, Anos 2000, Anos 80/90 e Funk & Rap BR.",
      "E o melhor: conecte sua conta do Spotify e jogue com as SUAS playlists e Músicas Curtidas. Contas Premium tocam a faixa completa direto do Spotify; sem Premium o jogo usa previews de 30 segundos — funciona do mesmo jeito. Compartilhe seus resultados em emojis e acompanhe suas estatísticas e sequência de vitórias.",
    ],
    controls: [
      { k: "▶", a: "Ouvir o trecho desbloqueado" },
      { k: "Digitar", a: "Buscar a música (autocomplete)" },
      { k: "Chutar", a: "Enviar o palpite" },
      { k: "⏭ Pular", a: "Gastar tentativa e liberar +trecho" },
      { k: "📋", a: "Compartilhar o resultado em emojis" },
    ],
    features: [
      { i: "🎧", t: "Trechos progressivos", d: "1s → 2s → 4s → 7s → 11s → 16s em 6 tentativas." },
      { i: "💚", t: "Conexão com Spotify", d: "Jogue com suas playlists e Músicas Curtidas." },
      { i: "👑", t: "Faixa completa (Premium)", d: "Player oficial do Spotify pra quem tem Premium." },
      { i: "📅", t: "Desafio Diário", d: "Uma música por dia, igual pra todo mundo." },
      { i: "🎼", t: "8 playlists Atenis", d: "Do sertanejo ao rock clássico, sem precisar de login." },
      { i: "📊", t: "Stats & compartilhar", d: "Sequência, distribuição e resultado em emojis." },
    ],
  },
  {
    id: "car3d",
    title: "City Drive 3D",
    short: "Dirija por uma cidade 3D viva com física de carro de verdade.",
    cat: "corrida",
    catName: "Corrida",
    rating: 4.8,
    plays: "6.3M",
    dev: "Atenis Studios",
    tags: ["Cidade", "Carros", "Simulação", "Direção", "Drift"],
    grad: "linear-gradient(135deg,#c0392b,#7a140f)",
    accent: "#ff5a4d",
    icon: "🏎️",
    playable: true,
    embed: "",
    src: "games/car3d/index.html?v=25",
    flags: ["TOP"],
    about: [
      "City Drive 3D coloca você ao volante numa cidade 3D gerada em tempo real: ruas com faixas, cruzamentos com semáforos, calçadas, prédios com janelas, postos, postes de luz e trânsito de carros com IA circulando pela malha viária.",
      "O destaque é a pegada de direção: o carro tem peso. A aceleração sobe de forma gradual (de 0 a 100 km/h em torno de 10 segundos), a esterçada fica mais suave em alta velocidade, a frenagem exige distância e o traseiro perde aderência de forma progressiva quando você puxa o freio de mão para derrapar.",
      "Suspensão com transferência de peso (o carro mergulha ao frear e senta ao acelerar), câmera com atraso, FOV dinâmico e tremor reforçam a sensação de velocidade. Tudo direto no navegador, sem instalar nada.",
    ],
    controls: [
      { k: "W / ↑", a: "Acelerar" },
      { k: "S / ↓", a: "Frear / Ré" },
      { k: "A · D", a: "Virar (mais suave em alta)" },
      { k: "Espaço", a: "Freio de mão (drift)" },
      { k: "Toque", a: "Piloto automático on/off" },
    ],
    features: [
      { i: "🏙️", t: "Cidade viva", d: "Ruas, cruzamentos, calçadas, prédios, posto e postes de luz." },
      { i: "⚖️", t: "Física com peso", d: "Aceleração gradual, inércia e momento de um carro real." },
      { i: "🛞", t: "Aderência progressiva", d: "Frenagem com distância e drift que exige controle." },
      { i: "🚦", t: "Trânsito com IA", d: "Carros circulando e parando nos semáforos." },
      { i: "🎢", t: "Suspensão", d: "Mergulha ao frear, senta ao acelerar, inclina nas curvas." },
      { i: "🎥", t: "Câmera dinâmica", d: "Atraso, FOV que abre na velocidade e tremor." },
    ],
  },
  {
    id: "paciencia",
    title: "Paciência",
    short: "O clássico Klondike, repaginado com o visual Atenis.",
    cat: "cartas",
    catName: "Cartas",
    rating: 4.9,
    plays: "9.1M",
    dev: "Atenis Studios",
    tags: ["Cartas", "Klondike", "Clássico", "Mesa"],
    grad: "linear-gradient(135deg,#1e6fb8,#0c3b66)",
    accent: "#4f9dff",
    icon: "🃏",
    playable: true,
    embed: "",
    src: "games/paciencia/index.html?v=4",
    flags: ["NEW"],
    about: [
      "Paciência é o eterno Klondike — aquele que acompanha gerações — reconstruído do zero com a identidade visual da Atenis: mesa em degradê azul-marinho, cartas nítidas e naipes de alto contraste.",
      "Organize as 52 cartas nas quatro bases, do Ás ao Rei por naipe, montando sequências descendentes de cores alternadas nas colunas. Compre do monte, planeje suas jogadas e limpe a mesa.",
      "Com desfazer ilimitado, auto-resolver e controles que funcionam tanto no toque quanto no desktop, é a Paciência mais confortável pra jogar a qualquer hora.",
    ],
    controls: [
      { k: "Clique", a: "Selecionar e mover carta" },
      { k: "Clique duplo", a: "Enviar carta para a base" },
      { k: "Monte", a: "Comprar nova carta" },
      { k: "U", a: "Desfazer jogada" },
      { k: "⚡ Auto", a: "Auto-resolver" },
    ],
    features: [
      { i: "🃏", t: "Klondike clássico", d: "Regras tradicionais, do Ás ao Rei nas bases." },
      { i: "↩️", t: "Desfazer ilimitado", d: "Volte quantas jogadas quiser sem perder o jogo." },
      { i: "⚡", t: "Auto-resolver", d: "Finaliza automaticamente quando o jogo está ganho." },
      { i: "⏱️", t: "Cronômetro & jogadas", d: "Acompanhe tempo e número de movimentos." },
      { i: "📱", t: "Toque & desktop", d: "Clique-e-clique fluido em qualquer tela." },
      { i: "🏆", t: "Tela de vitória", d: "Celebração ao limpar toda a mesa." },
    ],
  },
  {
    id: "reino",
    title: "The King's Decision",
    short: "Sente no trono. Diga SIM ou NÃO. Cada escolha muda o reino.",
    cat: "estrategia",
    catName: "Estratégia",
    rating: 4.9,
    plays: "4.2M",
    dev: "Atenis Studios",
    tags: ["Decisões", "Reino", "Narrativo", "Rogue-lite", "Medieval"],
    grad: "linear-gradient(135deg,#caa64b,#6b4a1a)",
    accent: "#e7c15a",
    icon: "👑",
    playable: true,
    embed: "",
    src: "games/reino/index.html?v=4",
    flags: ["NEW"],
    about: [
      "The King's Decision põe você no trono de um reino medieval. A cada dia, súditos — camponeses, nobres, cavaleiros, mercadores, magos, ladrões e personagens misteriosos — chegam à sala do trono com pedidos, dilemas e ameaças. Você só tem duas opções: SIM ou NÃO.",
      "Cada decisão move seis pilares do reino: Autoridade, Ouro, Felicidade, Exército, Saber e Fé. Se qualquer um chegar ao extremo, seu reinado termina — de um jeito diferente a cada vez. E nada é esquecido: a escolha de hoje volta semanas depois como recompensa... ou como vingança.",
      "Eventos aleatórios (incêndios, pestes, secas, dragões, festivais), múltiplos finais, conquistas e save automático garantem partidas curtas e muito rejogáveis. Inspirado em Reigns, Sort the Court e Yes Your Grace, com identidade própria.",
    ],
    controls: [
      { k: "SIM", a: "Aceitar o pedido" },
      { k: "NÃO", a: "Recusar o pedido" },
      { k: "Passar o mouse", a: "Ver quais atributos mudam" },
      { k: "☰ Menu", a: "Salvar e voltar ao início" },
      { k: "🔊", a: "Ligar/desligar o som" },
    ],
    features: [
      { i: "⚖️", t: "Seis pilares", d: "Autoridade, Ouro, Felicidade, Exército, Saber e Fé em equilíbrio." },
      { i: "🔗", t: "Consequências", d: "Decisões voltam dias depois como recompensa ou crise." },
      { i: "🎲", t: "Eventos aleatórios", d: "Incêndios, pestes, secas, dragões, festivais e mais." },
      { i: "🏁", t: "Múltiplos finais", d: "Revolução, Tirania, Idade do Ouro, Dinastia Eterna..." },
      { i: "🏆", t: "Conquistas & save", d: "Progresso salvo e troféus por feitos lendários." },
      { i: "🖼️", t: "Personagens via JSON", d: "Arquitetura pronta pra você adicionar retratos e falas." },
    ],
  },
  {
    id: "geoguesser",
    title: "Quizes",
    short: "Adivinhe o lugar do mundo pela imagem — quiz de geografia!",
    cat: "quizes",
    catName: "Quizes",
    rating: 4.7,
    plays: "1.2M",
    dev: "Atenis Games",
    tags: ["Quiz", "Geografia", "Mapa", "Mundo"],
    grad: "linear-gradient(135deg,#1aa06b,#0c5b3a)",
    accent: "#1aa06b",
    icon: "🌍",
    playable: true,
    embed: "https://geo-gesser.vercel.app",
    src: "https://geo-gesser.vercel.app",
    flags: ["NEW"],
    about: [
      "GeoGuesser é um quiz de geografia: você vê um lugar do mundo e tenta adivinhar onde ele fica marcando no mapa. Quanto mais perto do ponto certo, mais pontos você ganha.",
      "Teste seus conhecimentos de países, cidades e paisagens enquanto viaja o mundo sem sair da cadeira. Ótimo pra aprender geografia jogando.",
    ],
    controls: [
      { k: "Mouse", a: "Explorar e navegar no mapa" },
      { k: "Clique", a: "Marcar o local que você acha" },
      { k: "Confirmar", a: "Enviar o palpite e ver a pontuação" },
    ],
    features: [
      { i: "🌍", t: "Mundo todo", d: "Lugares dos quatro cantos do planeta." },
      { i: "🗺️", t: "Mapa interativo", d: "Navegue e marque seu palpite no mapa." },
      { i: "🏆", t: "Pontuação", d: "Quanto mais perto, mais pontos." },
      { i: "🧠", t: "Aprenda jogando", d: "Geografia de um jeito divertido." },
    ],
  },
  {
    id: "minado",
    title: "Campo Minado",
    short: "Cave os campos sem pisar nas minas — lógica e dedução!",
    cat: "puzzle",
    catName: "Puzzle",
    rating: 4.8,
    plays: "5.7M",
    dev: "Atenis Studios",
    tags: ["Puzzle", "Lógica", "Clássico", "Minas"],
    grad: "linear-gradient(135deg,#2b3954,#15203a)",
    accent: "#4f9dff",
    icon: "💣",
    playable: true,
    embed: "",
    src: "games/minado/index.html?v=5",
    flags: ["NEW"],
    about: [
      "Campo Minado é o clássico de lógica: revele todos os campos seguros sem cavar nenhuma mina. Cada número mostra quantas minas existem ao redor — use dedução para descobrir onde elas estão e marcá-las com bandeira.",
      "Interação fácil: 1 clique abre o menu (Cavar ou Bandeira), clique duplo cava na hora, e clicar num número já revelado abre os vizinhos automaticamente. Três dificuldades, cronômetro e recorde de tempo.",
    ],
    controls: [
      { k: "1 clique", a: "Abre o menu: Cavar ou Bandeira" },
      { k: "Clique duplo", a: "Cava direto (ou abre vizinhos)" },
      { k: "Clique direito", a: "Marca/tira a bandeira" },
      { k: "🙂", a: "Reiniciar a partida" },
    ],
    features: [
      { i: "🧠", t: "Pura lógica", d: "Deduza onde estão as minas pelos números." },
      { i: "🖱️", t: "Menu no clique", d: "Cavar ou marcar com um toque — ótimo no celular." },
      { i: "⚡", t: "Abertura automática", d: "Clique duplo abre vizinhos seguros (chord)." },
      { i: "🎚️", t: "3 dificuldades", d: "Fácil, Médio e Difícil." },
      { i: "⏱️", t: "Cronômetro & recorde", d: "Tente bater seu melhor tempo." },
      { i: "🚩", t: "Bandeiras", d: "Marque as minas e conte quantas faltam." },
    ],
  },
];

// utilidades
const byId = (id) => GAMES.find((g) => g.id === id);
const catCount = (cat) => GAMES.filter((g) => g.cat === cat).length;
